# Site
repository: shawnlawsure/shawnlawsure.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shawn Lawsure
title: Software Developer
email: slawsure@gmail.com
website: https://shawnlawsure.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  shawnlawsure
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: shawnlawsure
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  For over 25 years I have worked in the Information Systems field as both a full-time employee and an independent contractor for a variety of companies.

  I have extensive professional experience with numerous programming languages and technologies including C#, JavaScript (including related libraries like React, Vue, and jQuery), SQL, VB.NET, and ASP.NET as well as a working knowledge of a great variety of others.  I also have an advanced understanding of the concepts behind these technologies including Object-Oriented Programming, Relational Data, Functional Programming, MVC, and MVVM.
  
  I also have extensive professional experience using various database technologies, including SQLServer and mySQL, and have developed advanced skills in database design as well as SQL programming.
 
  For the past 4 or 5 years I have chosen to work primarily in front-end roles and to concentrate on learning technologies specific to the front-end. In my most recent professional role, I converted an existing Angular front-end application (SPA) to React using the latest recommendations including functional components and hooks. Prior to that, I was heavily involved in developing a webinar-like application using Vue and Nuxt.js.

  In nearly all of the work I have been involved with in the past 15 years I have played a lead role in the design as well as the development of the work.

  You are welcome to contact me anytime.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stamp Collector's Album (Front-end) - React/Redux
        link: github.com/shawnlawsure/stamp
        # link_text: Project Website
        additional_links:
          - title:  Stamp Collector's Catalog (Front-end) - React/Redux
            icon: fab fa-github
            url: github.com/shawnlawsure/stamp
        description: | # this will include new lines to allow paragraphs
          The frontend for a SPA written in <mark>React</mark> and <mark>Redux</mark>.  The app is intended to be used by stamp collectors to catalog and display their stamp collection.
      
      - layout: top-middle
        title: Stamp Collector's Album (Back-end) - Node.js/MySQL
        link: github.com/shawnlawsure/stamp-node
        # link_text: Project Website
        additional_links:
          - title:  Stamp Collector's Album (Back-end) - Node.js/MySQL
            icon: fab fa-github
            url: github.com/shawnlawsure/stamp-node
        description: | # this will include new lines to allow paragraphs
          The backend for a SPA using <mark>Node.js</mark> and <mark>MySQL</mark> that exposes a REST api.

      - layout: top-middle
        title: Zenith Controls - TypeScript
        link: github.com/shawnlawsure/zenith-controls
        # link_text: Project Website
        additional_links:
          - title:  Zenith Controls - TypeScript
            icon: fab fa-github
            url: github.com/shawnlawsure/zenith-controls
        description: | # this will include new lines to allow paragraphs
          A suite of web UI controls written in <mark>TypeScript</mark>.  Includes the following controls: Calendar, CheckBoxList, DropDown, Grid, ListBox, and TextBox.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Modularization and Encapsulation in JavaScript
        link: codeproject.com/Articles/1208822/Modularization-and-Encapsulation-in-JavaScript

      - layout: top-middle
        title: Beginning ReactJS By Example
        link: codeproject.com/Articles/1227248/Beginning-ReactJS-By-Example

      - layout: top-middle
        title: Knockout Code with KnockoutJS
        link: codeproject.com/Articles/1056775/Knockout-Code-with-KnockoutJS

      - layout: top-middle
        title: Easy JavaScript Generic List Implementation
        link: codeproject.com/Tips/378906/Easy-JavaScript-Generic-List-Implementation

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Watermark Insights
        link: https://www.watermarkinsights.com/
        # link_text: watermarkinsights.com
        sub_title: Senior Front-End Software Developer
        caption: Mar 2022 - Present
        quote: >
          JavaScript, React, Typescript, Webpack, Webpack Module Federation, Tailwind, Sitecore, ASP.NET
        description: | # this will include new lines to allow paragraphs
            Rewrite, from scratch, the UI for an existing ASP.NET application from Angular to React.

            Build React functional components at various levels of composition.

            Integrate the new React SPA with a Sitecore CMS back-end.

            Rewrite back-end API endpoints in ASP.NET using C# to support the new front-end UI.

            Configure the new front-end project using Webpack for both development and production builds/deployments.

      - layout: left
        title: ON24
        link: https://www.on24.com/
        # link_text: ON24.com
        sub_title: Full-Stack Software Developer
        caption: Feb 2021 - Mar 2022
        quote: >
          JavaScript, Vue.js, Nuxt.js, Webpack, Tailwind, Vuex, Redis
        description: | # this will include new lines to allow paragraphs
            Design and develop front-end pages and components for two large single-page web applications using JavaScript, Vue.js, Vuex, Nuxt.js, CSS, Tailwind, Webpack, Redis, and Axios.

            Lead the front-end team at times during the project.
      
      - layout: left
        title: Toolwatch
        link: https://www.toolwatch.com/
        # link_text: toolwatch.com
        sub_title: Full-Stack Software Developer
        caption: Sep 2020 - Feb 2021
        quote: >
          C#, JavaScript, Vue.js, Bootstrap, NUnit, .NET, WinForms, T-SQL
        description: | # this will include new lines to allow paragraphs
            Design and develop enhancements to a large enterprise-level operations management application for the construction industry using .NET, C#, WinForms, JavaScript, and Vue.js.

      - layout: left
        title: ProSearch, Inc.
        link: prosearchmaine.com
        sub_title: Senior Software Developer (Contract)
        caption: Feb 2019 - Nov 2019
        quote: >
          C#, JavaScript, Vue.js, .NET, T-SQL
        description: | # this will include new lines to allow paragraphs
            Design and develop browser-based insurance applications and corresponding back-end services using JavaScript, Vue.js, HTML5, CSS3, C# and T-SQL.

      - layout: left
        title: Tri-Plus Services, Inc.
        link: triplusservices.com
        sub_title: Senior Application and Database Developer
        caption: Nov 2017 - Apr 2018
        quote: >
          C#, WPF, .NET, T-SQL, WCF
        description: | # this will include new lines to allow paragraphs
            Design and develop enhancements to a large WPF desktop application, including the associated WCF services and SqlServer databases, used for administering Long-Term Care insurance.

      - layout: left
        title: Common Census, Inc.
        link: commoncensus.com
        sub_title: Software Developer
        caption: Oct 2015 - Nov 2017
        quote: >
          C#, VB.NET, ASP.NET, JavaScript, Knockout.js, Bootstrap, T-SQL
        description: | # this will include new lines to allow paragraphs
            Designed and developed enhancements to a large enterprise-level employee benefits application written in ASP.NET, C#, VB.NET, JavaScript and a variety of client-side libraries and frameworks including Bootstrap and Knockout.

      - layout: left
        title: Diversified Communications
        link: www.divcom.com
        sub_title: Application Development Manager/Senior Application Developer
        caption: Mar 2010 - Sep 2015
        quote: >
          C#, ASP.NET, JavaScript, T-SQL, Joomla, Salesforce, APEX, SalesLogix, GP Dynamics, SSRS
        description: | # this will include new lines to allow paragraphs
            Managed a team of senior-level developers.

            Provided technical leadership for all enterprise applications including, but not limited to, CRM (Salesforce), Financial (GP Dynamics), Invoicing (custom), Master Data Management (custom), Reporting (SSRS), and external web sites (Joomla).
            
            Developed and provided technical leadership for transitioning our old CRM to Salesforce; including creating triggers, components and classes in addition to integrating with external systems/databases.
            
            Architected/designed all new systems including the integrations between them.
            
            Managed and helped implement small to mid-size IT projects including the conversion of our external websites from Ektron to Joomla and from Joomla to WordPress.
            
            Customized and maintained a third-party CRM web application (SalesLogix) written primarily in ASP.NET and C# with SqlServer.
            
            Designed and developed custom applications (ASP.NET, C#, JavaScript) that integrate marketing, accounting, and sales.
            
            Designed and developed a master data management web application (ASP.NET, C#, JavaScript) and database (SqlServer) along with a batch process to perform de-duplication and record linking from many sources of contact and company data.

      - layout: left
        title: Independent Software Developer
        link: www.divcom.com
        sub_title: test
        caption: Sep 2009 - Aug 2015
        quote: >
          C#, ASP.NET, JavaScript, MySQL, WCF, Silverlight, ADO.NET
        description: | # this will include new lines to allow paragraphs
            <b>University Disability Consortium, Newton, MA</b>
              - Developed a web application using ASP.NET, C#, JavaScript, WCF, and MySql to manage referrals and associated documents for use by employees, consultants, and clients.

            <b>Professional Disability Associates, Portland, ME</b>
              - Developed a SharePoint site primarily focused on sharing medical documents between employees, consultants, and clients.
              - Developed a claim management system using Silverlight, WCF, ADO.NET Data Services, and ADO.NET Entity Data Modeling.

            <b>Dial Medical Direct Inc, South Portland, ME</b>
              - Developed functionality within Microsoft Access that creates Health Care Claim Professional (837P) EDI documents.
              - Developed and implemented a delivery confirmation application that interfaces with UPS and USPS using XML-based web services.

      - layout: left
        title: AMS Services
        link: 
        sub_title: Senior Software Engineer
        caption: Sep 2006 - Feb 2010
        quote: >
          C#, ASP.NET, WWF, WPF, WCF, XML, SqlServer, Oracle
        description: | # this will include new lines to allow paragraphs
            Designed and developed custom workflow activities for UI page processing in Microsoft’s Windows Workflow Foundation.
            
            Developed a Windows Presentation Foundation application to allow clients to create customized web pages from database schema.
            
            Designed and developed XML-based ASP.NET Web services (C#) that access SqlServer and Oracle databases and integrated these services with an existing insurance policy processing client application.
            
            Designed and developed a WPF-based client UI and associated business service that utilizes the above Web services.
            
            Converted ASP.NET Web services to WCF services.

      - layout: left
        title: Aetna (formerly Broadspire, Inc.)
        link: aetna.com
        sub_title: Senior Software Engineer
        caption: May 2002 - Sep 2006
        quote: >
          VB.NET, ASP.NET, Oracle
        description: | # this will include new lines to allow paragraphs
            Designed and developed a Web-based “script engine” and an associated “script maintenance” application that allows business analysts to build their own scripts for data intake through the Web (VB.NET and ASP.NET 2.0).
            
            Designed and developed major enhancements to a Web-based absence management application (VB.NET and ASP.NET 2.0).
            
            Rewrote major parts of the existing code base using a Microsoft-based software architecture that includes the implementation of Business Entities and Business Process Components to make the code base more maintainable and efficient.

      - layout: left
        title: DeLorme, Inc.
        link: garmin.com
        sub_title: Software Engineer
        caption: Apr 2000 - Apr 2002
        quote: >
          C++, COM
        description: | # this will include new lines to allow paragraphs
          Maintained and enhanced a set of GIS software components (C++ and COM) used in a variety of world-re-known mapping software products.  These components include a GPS interface, an Internet download component, and a map printing component.
          
          Worked closely with a user interface design group in analyzing and designing new interfaces for software components.

      - layout: left
        title: Allenbrook, Inc.
        link: 
        sub_title: Software Developer
        caption: Sep 1996 - Apr 2000
        quote: >
          C++, COM, Centura, Oracle, SqlServer, SQLBase
        description: | # this will include new lines to allow paragraphs
          Designed and developed major enhancements to, as well as maintained and supported, a tool-based client/server insurance policy processing system (including, but not limited to, policy entry, billing, commissions and rating) using Centura Team Developer, Visual C++, and COM.
          
          Designed, developed, and gathered requirements for a major insurance tool sub-set used to process Premium Audits and integrated this new functionality into the existing tool set.
          
          Develop database scripts for Oracle, SqlServer, and SQLBase.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boston University
        caption: 1987 - 1991
        sub_title: BS Computer Science
        quote: >

        description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my keen interest in software development some of my other interests and hobbies include:
      - Golf
      - Biking
      - Piano
      - Cooking
      - Literature

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
