# Site
repository: shawnlawsure/shawnlawsure.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shawn Lawsure
title: Software Developer
email: slawsure@gmail.com
website: https://shawnlawsure.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  shawnlawsure
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: shawnlawsure
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  For over 25 years I have worked in the Information Systems field as both a full-time employee and an independent contractor for a variety of companies.

  I have extensive professional experience with numerous programming languages and technologies including C#, JavaScript (including related libraries like jQuery, React, Knockout, and Vue), SQL, VB.NET, and ASP.NET as well as a working knowledge of a variety of others.  I have an advanced understanding of the concepts behind these technologies including Object-Oriented Programming, Relational Data, Functional Programming, MVC and MVVM.

  I also have extensive professional experience using various database technologies, including SQLServer and mySQL, and have developed advanced skills in database design as well as SQL programming.
 
  In nearly all of the work I have been involved with in the past 15 years I have played a lead role in the design as well as the development of the work.

  You are welcome to contact me anytime.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stamp Collector's Album (Front-end) - React/Redux
        link: github.com/shawnlawsure/stamp
        # link_text: Project Website
        additional_links:
          - title:  Stamp Collector's Catalog (Front-end) - React/Redux
            icon: fab fa-github
            url: github.com/shawnlawsure/stamp
        description: | # this will include new lines to allow paragraphs
          The frontend for a SPA written in <mark>React</mark> and <mark>Redux</mark>.  The app is intended to be used by stamp collectors to catalog and display their stamp collection.
      
      - layout: top-middle
        title: Stamp Collector's Album (Back-end) - Node.js/MySQL
        link: github.com/shawnlawsure/stamp-node
        # link_text: Project Website
        additional_links:
          - title:  Stamp Collector's Album (Back-end) - Node.js/MySQL
            icon: fab fa-github
            url: github.com/shawnlawsure/stamp-node
        description: | # this will include new lines to allow paragraphs
          The backend for a SPA using <mark>Node.js</mark> and <mark>MySQL</mark> that exposes a REST api.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Toolwatch
        link: toolwatch.com
        # link_text: toolwatch.com
        sub_title: Full-Stack Software Developer
        caption: Sep 2020 - Present
        quote: >
          C#, JavaScript, Vue.js, Bootstrap, NUnit, .NET, WinForms, T-SQL
        description: | # this will include new lines to allow paragraphs
            Design and develop enhancements to a large enterprise-level operations management application for the construction industry using .NET, C#, WinForms, JavaScript, and Vue.js.

      - layout: left
        title: ProSearch, Inc.
        link: prosearchmaine.com
        sub_title: Senior Software Developer (Contract)
        caption: Feb 2019 - Nov 2019
        quote: >
          C#, JavaScript, Vue.js, .NET, T-SQL
        description: | # this will include new lines to allow paragraphs
            Design and develop browser-based insurance applications and corresponding back-end services using JavaScript, Vue.js, HTML5, CSS3, C# and T-SQL.

      - layout: left
        title: Tri-Plus Services, Inc.
        link: triplusservices.com
        sub_title: Senior Application and Database Developer
        caption: Nov 2017 - Apr 2018
        quote: >
          C#, WPF, .NET, T-SQL, WCF
        description: | # this will include new lines to allow paragraphs
            Design and develop enhancements to a large WPF desktop application, including the associated WCF services and SqlServer databases, used for administering Long-Term Care insurance.

      - layout: left
        title: Common Census, Inc.
        link: commoncensus.com
        sub_title: Software Developer
        caption: Oct 2015 - Nov 2017
        quote: >
          C#, VB.NET, ASP.NET, JavaScript, Knockout.js, Bootstrap, T-SQL
        description: | # this will include new lines to allow paragraphs
            Designed and developed enhancements to a large enterprise-level employee benefits application written in ASP.NET, C#, VB.NET, JavaScript and a variety of client-side libraries and frameworks including Bootstrap and Knockout.

      - layout: left
        title: Diversified Communications
        link: www.divcom.com
        sub_title: Application Development Manager/Senior Application Developer
        caption: Mar 2010 - Sep 2015
        quote: >
          C#, ASP.NET, JavaScript, T-SQL, Joomla, Salesforce, APEX, SalesLogix, GP Dynamics, SSRS
        description: | # this will include new lines to allow paragraphs
            Managed a team of senior-level developers.

            Provided technical leadership for all enterprise applications including, but not limited to, CRM (Salesforce), Financial (GP Dynamics), Invoicing (custom), Master Data Management (custom), Reporting (SSRS), and external web sites (Joomla).
            
            Developed and provided technical leadership for transitioning our old CRM to Salesforce; including creating triggers, components and classes in addition to integrating with external systems/databases.
            
            Architected/designed all new systems including the integrations between them.
            
            Managed and helped implement small to mid-size IT projects including the conversion of our external websites from Ektron to Joomla and from Joomla to WordPress.
            
            Customized and maintained a third-party CRM web application (SalesLogix) written primarily in ASP.NET and C# with SqlServer.
            
            Designed and developed custom applications (ASP.NET, C#, JavaScript) that integrate marketing, accounting, and sales.
            
            Designed and developed a master data management web application (ASP.NET, C#, JavaScript) and database (SqlServer) along with a batch process to perform de-duplication and record linking from many sources of contact and company data.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boston University
        caption: 1987 - 1991
        sub_title: BS Computer Science
        quote: >

        description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my keen interest in software development some of my other interests and hobbies include:
      - Golf
      - Biking
      - Piano
      - Cooking
      - Literature

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
